import type { CityData } from "@/components/CityServicePage";

export const khobar: CityData = {
  slug: "khobar",
  landmarks: [
    { name: "Khobar Corniche", description: "A lively waterfront strip of cafés and walkways facing the Gulf, generally busier and more built-up than Dammam\'s own Corniche." },
    { name: "Al Rashid Mall", description: "One of the Eastern Province\'s largest retail centres, a common meeting and pickup point for shoppers coming from Dammam or Dhahran." },
    { name: "King Fahd Causeway approach", description: "Khobar sits closest to the causeway crossing into Bahrain, making it the natural staging point for weekend trips across the border." },
  ],
  seasonalNote: "Thursday and Friday evenings see a noticeable surge of traffic toward the King Fahd Causeway as residents head to Bahrain for the weekend — plan border-crossing pickups outside that window if you want to avoid the queue. Like the rest of the Eastern Province, summer humidity is significant.",
  tags: ["business"],
  priority: 2,
  nearbyCities: [{ city: "Jubail", slug: "jubail" }, { city: "Riyadh", slug: "riyadh" }],
  city: "Khobar",
  h1: "Private Taxi, Airport Transfer & Chauffeur Service in Khobar",
  region: "Eastern Province",
  intro: "Premium taxi services in Al Khobar — business transfers, airport pickups from King Fahd International, and intercity routes across the Eastern Province.",
  whyVisit: "Al Khobar is the Eastern Province's commercial and leisure hub — home to the famous Khobar Corniche, upscale shopping malls, and proximity to Saudi Aramco's Dhahran headquarters. It's a key destination for business travelers and Gulf tourists alike.",
  challenge: "Al Khobar's rapid growth means traffic between the city centre, Corniche, and the airport can be unpredictable. Visitors often need reliable point-to-point transfers without the complexity of metered taxis.",
  benefit: "Our fixed-rate transfers connect Khobar to King Fahd International Airport, neighboring Dammam and Dhahran, and corporate venues — with executive vehicles suitable for business clients.",
  airport: { name: "King Fahd International Airport", code: "DMM", distance: "25 km from Khobar city centre" },
  popularRoutes: [
    { from: "Khobar", to: "DMM Airport", time: "25–35 min" },
    { from: "Khobar", to: "Dammam / Dhahran", time: "15–25 min" },
    { from: "Khobar", to: "Jubail", time: "~1 hr" },
  ],
  pickupPoints: ["Khobar Corniche", "Al Rashid Mall", "Dhahran Mall", "Half Moon Bay Road hotels", "Prince Turki Street", "Khobar business district"],
  faqs: [
    { q: "Is Khobar covered in your Eastern Province service?", a: "Yes — Khobar is a primary service city. We cover all districts including Half Moon Bay and the Corniche." },
    { q: "Can I book a transfer from Khobar to Jubail?", a: "Yes, Khobar to Jubail Industrial City is a regular route — approximately 1 hour drive." },
    { q: "Do you have female-friendly vehicle options?", a: "Yes — all our vehicles are private and driven by vetted, licensed drivers. Female passengers travel in comfort and privacy." },
    { q: "Can you take me across the King Fahd Causeway to Bahrain?", a: "Yes — Khobar sits closest to the causeway of any Eastern Province city, making it the natural starting point for a Bahrain crossing." },
    { q: "Is Khobar busier than Dammam?", a: "Its Corniche and retail district (including Al Rashid Mall) tend to be livelier and more built-up than Dammam's equivalent areas, especially in the evenings." },
    { q: "Is weekend traffic to Bahrain really that noticeable?", a: "Yes — Thursday and Friday evenings see a real surge toward the causeway as residents head over for the weekend. Booking outside that window avoids the queue entirely." },
    { q: "How humid is Khobar in summer?", a: "Very — like the rest of the Eastern Province coast, humidity peaks from June through September, making evenings notably more pleasant than midday for the Corniche." },
    { q: "Is Khobar's Corniche walkable from most hotels?", a: "Many business hotels along Prince Turki Street are within a short drive of the Corniche — your driver can confirm the exact distance for your specific hotel." },
    { q: "Do you serve Half Moon Bay for weekend trips?", a: "Yes — Half Moon Bay Road hotels and the beach area are within our standard Khobar coverage, no extra surcharge." },
  ],
  reviews: [
    { name: "Patricia M.", origin: "Expat, USA", text: "Reliable, clean, and professional. My go-to service for Khobar–Airport transfers." },
    { name: "Yousef A.", origin: "Business Client, Khobar", text: "Booked for our corporate guests every visit. Never a complaint." },
    { name: "Emma L.", origin: "Tourist, Australia", text: "Khobar Corniche to the airport was smooth and stress-free." },
  ],
  heroImage: "/destinations/dammam-eastern-province-skyline.webp",
  heroImageAlt: "Eastern Province waterfront near Al Khobar — private chauffeur service in the Dammam metropolitan area",
  serviceAreas: [
    { name: "Khobar Corniche", note: "The Eastern Province's liveliest waterfront strip of cafés and walkways, busier and more built-up than Dammam's own Corniche." },
    { name: "Al Rashid Mall district", note: "One of the region's largest retail centres and a common meeting point for shoppers from Dammam or Dhahran." },
    { name: "Prince Turki Street", note: "Khobar's main business corridor, lined with offices and corporate hotels." },
  ],
  hotelZones: [
    { name: "Prince Turki Street business hotels", note: "Khobar's densest cluster of hotels serving business travelers." },
    { name: "Corniche hotel strip", note: "Waterfront hotels popular with leisure visitors and Gulf tourists." },
    { name: "Half Moon Bay Road", note: "Resort-style stays along the coast south of the city centre." },
  ],
  airportNote: "King Fahd International Airport sits about 25km from Khobar — the same airport used by neighbouring Dammam and Dhahran, so the transfer time is broadly similar from any of the three cities.",
  businessTravel: {
    intro: "Al Khobar is the Eastern Province's commercial and leisure hub, and a regular base for business travelers whose meetings span Khobar, Dhahran and Dammam in the same trip.",
    areas: [
      { name: "Prince Turki Street", note: "Khobar's main office corridor, a frequent multi-stop meeting day pickup point." },
      { name: "Al Rashid Mall area", note: "A common venue for client meetings and casual business meals." },
      { name: "King Fahd Causeway", note: "The natural staging point for cross-border business trips into Bahrain — Khobar sits closest to the crossing of any Eastern Province city." },
    ],
  },
  practicalInfo: [
    { title: "Causeway weekend surge", note: "Thursday and Friday evenings see a noticeable surge toward the King Fahd Causeway — plan border-crossing pickups outside that window to avoid the queue." },
    { title: "Summer humidity", note: "Significant from June through September, like the rest of the Eastern Province coast — evenings are more comfortable than midday." },
    { title: "Rapid growth", note: "Khobar's fast development means traffic patterns between the centre, Corniche and airport can shift — we plan routes with current conditions in mind rather than a fixed assumption." },
  ],
};

export const jubail: CityData = {
  slug: "jubail",
  landmarks: [
    { name: "Jubail Industrial City", description: "One of the largest industrial cities in the world, built around petrochemical and steel manufacturing — most visitors here are on business rather than sightseeing." },
    { name: "Jubail Corniche", description: "A quieter waterfront stretch than Dammam or Khobar\'s, popular with residents rather than tourists." },
    { name: "Fanateer Beach", description: "A local beach area on Jubail\'s coastline, a common weekend destination for families based in the city." },
  ],
  seasonalNote: "Jubail\'s traffic patterns follow industrial shift changes rather than tourism — expect predictable surges around the Royal Commission and major plant gates at shift-change times on weekdays, and much quieter roads on Fridays.",
  tags: ["business"],
  priority: 2,
  nearbyCities: [{ city: "Khobar", slug: "khobar" }, { city: "Dammam", slug: "dammam" }],
  city: "Jubail",
  h1: "Executive Car Service & Car Transfer in Jubail & Nearby Areas",
  region: "Eastern Province",
  intro: "Reliable taxi services in Jubail and Jubail Industrial City — corporate transfers, airport connections, and intercity routes for the Eastern Province's industrial capital.",
  whyVisit: "Jubail Industrial City is one of the world's largest industrial complexes, hosting major petrochemical companies, SABIC facilities, and hundreds of international contractors. It draws thousands of business travelers from around the globe each year.",
  challenge: "Jubail's industrial layout means transfers between the residential areas, industrial zones, and King Fahd International Airport require a knowledgeable driver familiar with security checkpoints and restricted access zones.",
  benefit: "Our Jubail service is tailored for corporate clients — pre-approved drivers, executive sedans and SUVs, and reliable timing for shift changes, contractor site visits, and executive airport runs.",
  airport: { name: "King Fahd International Airport", code: "DMM", distance: "80 km from Jubail" },
  popularRoutes: [
    { from: "Jubail Industrial City", to: "DMM Airport", time: "~1 hr" },
    { from: "Jubail", to: "Dammam / Khobar", time: "~1 hr" },
    { from: "Jubail", to: "Riyadh", time: "~3.5 hrs" },
  ],
  pickupPoints: ["Jubail Industrial City gates", "SABIC headquarters", "Jubail residential area hotels", "Royal Commission guesthouses", "Fanateer Beach", "Jubail Commercial Area"],
  faqs: [
    { q: "Do your drivers have access to Jubail Industrial City?", a: "Our drivers are familiar with all major entry gates and contractor procedures for the Industrial City." },
    { q: "Can you handle regular corporate shuttle contracts in Jubail?", a: "Yes — we offer monthly retainer contracts for companies needing recurring staff transfers in Jubail." },
    { q: "Is there a direct transfer from Jubail to Riyadh?", a: "Yes — approximately 3.5 hours via the Jubail–Dammam–Riyadh expressway. Book at least 24 hours in advance." },
    { q: "Do your pickup times work around shift changes?", a: "Yes — Jubail's traffic follows industrial shift patterns rather than typical rush hours, and our drivers plan around the major plant gate shift-change times." },
    { q: "Is Jubail mainly a business destination?", a: "Mostly, yes — most visitors are here for the Industrial City or Royal Commission work rather than tourism, though the Corniche and Fanateer Beach are popular with residents." },
    { q: "Do you offer airport transfers to Jubail specifically?", a: "Jubail doesn't have its own airport, so most visitors connect via Dammam's King Fahd International Airport — we run this transfer regularly for contractor arrivals." },
    { q: "Is Jubail quieter than Dammam or Khobar?", a: "Generally, yes — its Corniche and beach areas see far more residents than tourists, and traffic follows industrial shift patterns rather than typical weekend leisure surges." },
    { q: "Do you require advance notice for Industrial City gate access?", a: "Same-day bookings are usually fine, but for first-time contractor arrivals we recommend confirming your exact gate and badge requirements a day ahead so the driver isn't held up at security." },
    { q: "Is Jubail connected directly to Dammam's airport?", a: "There's no direct rail or shuttle link — our private transfer is the standard way contractors and visitors connect between King Fahd International Airport and Jubail, about an hour's drive." },
  ],
  reviews: [
    { name: "David H.", origin: "Contractor, Netherlands", text: "Used Gulf Trip for 3 months of Jubail–Airport transfers. Faultless every time." },
    { name: "Chen W.", origin: "Project Manager, Singapore", text: "Arranged transfers for our entire site team. Professional and cost-effective." },
    { name: "Khalid S.", origin: "Saudi Aramco, Jubail", text: "Best corporate taxi option in Jubail. Highly recommend." },
  ],
  heroImage: "/destinations/dammam-eastern-province-skyline.webp",
  heroImageAlt: "Eastern Province skyline near Jubail Industrial City — private chauffeur and corporate transfer service",
  serviceAreas: [
    { name: "Jubail Industrial City gates", note: "Multiple entry gates serve the industrial zone — drivers confirm which one matches your site pass before pickup." },
    { name: "Royal Commission residential area", note: "The planned residential district housing most Royal Commission and contractor staff." },
    { name: "Fanateer Beach & Corniche", note: "Jubail's quieter waterfront, popular with residents on weekends." },
  ],
  hotelZones: [
    { name: "Royal Commission guesthouses", note: "The main short-stay accommodation used by visiting contractors and Royal Commission guests." },
    { name: "Jubail Commercial Area", note: "A smaller cluster of commercial-district hotels, limited compared to Dammam or Khobar." },
  ],
  airportNote: "Jubail has no airport of its own — nearly every visitor connects via King Fahd International Airport in Dammam, about an hour's drive south.",
  businessTravel: {
    intro: "Jubail Industrial City is one of the world's largest industrial complexes, and almost every booking here is business-related — contractor site visits, SABIC and petrochemical company transfers, and shift-timed staff pickups.",
    areas: [
      { name: "Jubail Industrial City gates", note: "Drivers familiar with major entry gates and contractor entry procedures." },
      { name: "SABIC headquarters area", note: "A regular stop for corporate and technical visitors." },
      { name: "Royal Commission offices", note: "Administrative offices tied to the wider Industrial City operation." },
    ],
  },
  practicalInfo: [
    { title: "Shift-change traffic", note: "Jubail's traffic follows industrial shift changes rather than typical rush hours — expect predictable surges around major plant gates on weekdays." },
    { title: "Quiet Fridays", note: "Roads are noticeably quieter on Fridays, in contrast to the weekday shift-driven pattern." },
    { title: "No local airport", note: "Every airport connection routes through Dammam, about an hour away — factor this into arrival planning." },
  ],
};

export const taif: CityData = {
  slug: "taif",
  landmarks: [
    { name: "Al Hada Mountain Road", description: "A dramatic, switchback mountain road connecting Taif down toward Makkah, with a cable car offering views over the escarpment — best experienced with a driver used to the route." },
    { name: "Taif Rose Fields", description: "The source of Taif\'s famous rose oil, with harvest season drawing visitors to see (and smell) the fields in bloom." },
    { name: "Shubra Palace", description: "A 19th-century Ottoman-era palace in the city centre, now a small museum and one of Taif\'s few formal historic sites." },
    { name: "Al Shafa", description: "A cooler, forested highland area above the city, popular as a summer escape from the heat of the coast." },
  ],
  seasonalNote: "The Taif rose harvest (roughly March into early April) draws visitors specifically for the bloom and the seasonal rose-water souks. Taif\'s elevation makes it noticeably cooler than Makkah or Jeddah in summer, so it sees a steady influx of domestic travelers escaping the coastal heat from June through August.",
  tags: ["tourism"],
  priority: 2,
  nearbyCities: [{ city: "Makkah", slug: "makkah" }, { city: "Abha", slug: "abha" }],
  city: "Taif",
  h1: "Private Taxi & Private Car Service in Taif — Professional & Reliable",
  region: "Makkah Province",
  intro: "Comfortable taxi services in Taif — transfers from Taif Regional Airport, Makkah day trips, rose farm excursions, and Al-Hada/Al-Shafa mountain resort transfers.",
  whyVisit: "Taif, the 'City of Roses,' sits 1,800m above sea level in the Hejaz mountains. Known for its fragrant rose farms (producing most of the world's rose water and oud oil), honey markets, and cool summer climate — it's one of Saudi Arabia's most beloved domestic tourism destinations.",
  challenge: "Taif is 85km from Makkah via mountain roads and is frequently visited as a day trip. Its spread-out layout — from Al-Hada cable car to Shubra Palace to the rose farms — requires a vehicle for the full experience.",
  benefit: "We provide the ideal Taif experience: full-day tour transfers, Makkah–Taif direct routes, and airport pickups — with drivers who know every rose farm, honey vendor, and scenic overlook.",
  airport: { name: "Taif Regional Airport", code: "TIF", distance: "30 km from city centre" },
  popularRoutes: [
    { from: "Taif Airport (TIF)", to: "Taif city / Al-Hada", time: "30–40 min" },
    { from: "Taif", to: "Makkah", time: "~1.5 hrs" },
    { from: "Taif", to: "Jeddah", time: "~2 hrs" },
  ],
  pickupPoints: ["Taif Regional Airport", "Shubra Palace", "Al-Hada resort area", "Al-Shafa mountain village", "Taif Rose Festival grounds", "Souq Al-Dabab honey market"],
  faqs: [
    { q: "Can I do a Makkah–Taif day trip?", a: "Yes — this is one of our most popular routes. We offer round-trip day-trip packages from Makkah or Jeddah to Taif." },
    { q: "Is the road to Taif safe?", a: "The Al-Hada road is a beautiful mountain highway. Our drivers are experienced on this route year-round, including in winter fog conditions." },
    { q: "Do you cover the Al-Hada cable car area?", a: "Yes — Al-Hada and Al-Shafa are within our Taif service zone, including cable car entrance pickups." },
    { q: "When is Taif's rose season?", a: "Roughly March into early April — the fields are in bloom and the rose-water souks are at their busiest, so book ahead if you're visiting specifically for the harvest." },
    { q: "Is Taif cooler than Makkah or Jeddah?", a: "Yes, noticeably — the elevation makes a real difference, which is exactly why Taif sees a steady wave of domestic visitors escaping the coastal heat from June through August." },
    { q: "Is Al-Hada cable car included in a tour, or booked separately?", a: "The cable car ticket itself is booked on-site; we handle the transfer to and from the entrance and can time your visit around quieter hours." },
    { q: "Can I do Taif as a day trip from Jeddah?", a: "Yes — it's about 2 hours from Jeddah, and many visitors combine it with a stop in Makkah on the same day." },
  ],
  reviews: [
    { name: "Nora Al-Zahrani", origin: "Tourist, Riyadh", text: "The rose farm tour was magical. Our driver took us to hidden spots only locals know." },
    { name: "Omar F.", origin: "Family Traveler, Jeddah", text: "Taif in summer with kids — the cable car, the honey market, all covered in one day. Perfect service." },
    { name: "Michael T.", origin: "Traveler, UK", text: "Driver was a Taif native and gave us an authentic experience. Highly recommend." },
  ],
  heroImage: "/destinations/taif-mountain-city-view.webp",
  heroImageAlt: "Taif mountain city view in the Sarawat range — private transfer service to Saudi Arabia's rose-growing highlands",
  serviceAreas: [
    { name: "Taif city centre & Souq Al-Dabab", note: "The commercial core, home to the honey market and Shubra Palace." },
    { name: "Al-Hada & Al-Shafa mountain area", note: "The cable car and highland villages above the city, reached via the switchback mountain road." },
    { name: "Rose Farm district", note: "The rose-growing valleys just outside the city, busiest during the March–April harvest." },
  ],
  hotelZones: [
    { name: "Taif city-centre hotels", note: "The most convenient base for the Souq and Shubra Palace." },
    { name: "Al-Hada resort-area hotels", note: "Mountain-view stays popular with summer visitors escaping the coastal heat." },
  ],
  airportNote: "Taif Regional Airport sits about 30km from the city, along the mountain road down toward Makkah — allow extra time if you're continuing on to Makkah the same day.",
  practicalInfo: [
    { title: "Rose season", note: "Roughly March into early April — the fields are in bloom and rose-water souks are busiest, so book ahead if visiting specifically for the harvest." },
    { title: "Summer cooling effect", note: "Taif's elevation keeps it noticeably cooler than Makkah or Jeddah, drawing a steady wave of domestic visitors from June through August." },
    { title: "Mountain road driving", note: "The Al-Hada road can see winter fog — our drivers are experienced on the route year-round." },
  ],
};

export const abha: CityData = {
  slug: "abha",
  landmarks: [
    { name: "Al Souda", description: "The highest point in Saudi Arabia, with a cable car climbing through cloud forest — consistently the coolest spot in the country and one of the main reasons visitors come to Asir." },
    { name: "Abha Lake Park", description: "A large park built around an artificial lake in the city, popular for evening walks and one of Abha\'s most central family destinations." },
    { name: "Habala", description: "A former hanging village built into a cliff face, historically accessible only by rope — now reached by cable car and popular for the dramatic setting." },
  ],
  seasonalNote: "Abha\'s mountain elevation keeps it noticeably cooler than almost anywhere else in the Kingdom, which draws a steady wave of domestic tourism specifically in the summer months (June–August) as visitors escape the heat elsewhere — book ahead if traveling then, since hotels and drivers both get busier.",
  tags: ["tourism"],
  priority: 2,
  nearbyCities: [{ city: "Makkah", slug: "makkah" }, { city: "Taif", slug: "taif" }, { city: "Khamis Mushait", slug: "khamis-mushait" }],
  city: "Abha",
  h1: "Chauffeur Service & Executive Car Service in Abha & Nearby Areas",
  region: "Asir Province",
  intro: "Scenic taxi services in Abha and the Asir region — airport transfers, cable car excursions, mountain village tours, and connections to Jizan and Najran.",
  whyVisit: "Abha is Saudi Arabia's mountain tourism capital — situated at 2,200m above sea level in the Asir highlands. Its cool misty climate, dramatic escarpments, traditional Asiri villages, and the famous Abha cable car have made it one of Saudi Tourism's most marketed destinations.",
  challenge: "Abha's mountainous terrain makes navigation challenging for visitors. The distances between the city, Habala hanging village, Green Mountain, Rijal Alma historical village, and the cable car station require reliable local transport.",
  benefit: "Our Abha-based drivers are local experts who know every mountain road, seasonal viewpoint, and hidden village. We combine airport transfers with full-day mountain discovery tours.",
  airport: { name: "Abha International Airport", code: "AHB", distance: "22 km from city centre" },
  popularRoutes: [
    { from: "Abha Airport (AHB)", to: "Abha city centre", time: "25–35 min" },
    { from: "Abha", to: "Jizan", time: "~2.5 hrs" },
    { from: "Abha", to: "Najran", time: "~3 hrs" },
  ],
  pickupPoints: ["Abha International Airport", "Abha Palace Hotel", "Green Mountain cable car", "Habala village descent", "Rijal Alma Heritage Village", "Al-Soudah Park"],
  faqs: [
    { q: "Is Abha accessible year-round?", a: "Yes — though summer (June–September) is peak season. Roads can be misty in winter but are safe with experienced drivers." },
    { q: "Can you combine an Abha airport pickup with a tour?", a: "Yes — many guests book an airport pickup combined with a same-day Habala or Al-Soudah tour before hotel check-in." },
    { q: "Do you cover Rijal Alma from Abha?", a: "Yes — Rijal Alma is approximately 45 minutes from Abha and a popular add-on to any Asir itinerary." },
    { q: "Why is Abha busier in summer than most Saudi cities?", a: "Its mountain elevation keeps temperatures well below the rest of the Kingdom, which draws a steady wave of domestic tourists specifically escaping the heat from June through August." },
    { q: "Is Al Souda worth the trip from central Abha?", a: "Yes — it's the highest point in Saudi Arabia, with a cable car through cloud forest, and it's a fairly short, scenic drive from the city." },
    { q: "Can you take me to Habala village?", a: "Yes — the former hanging village is now reached by cable car rather than rope, and it's a popular half-day trip from Abha for the dramatic cliffside setting alone." },
    { q: "Is Abha good for family trips?", a: "Yes — Abha Lake Park and the Al-Souda cable car are both straightforward with children, and the cooler climate is easier on families than the coastal cities in summer." },
    { q: "Can you connect Abha with Khamis Mushait in the same booking?", a: "Yes — the two cities are about 20–25 minutes apart and are commonly combined in one Asir Province itinerary." },
  ],
  reviews: [
    { name: "Sara M.", origin: "Tourist, Jordan", text: "The mountain views from our car were breathtaking. Driver knew every scenic stop." },
    { name: "Abdullah K.", origin: "Family Traveler, Riyadh", text: "Abha with children was unforgettable. Reliable transfers made it stress-free." },
    { name: "Lena P.", origin: "Traveler, Germany", text: "Habala village tour from Abha — extraordinary. Gulf Trip made it seamless." },
  ],
  heroImage: "/destinations/abha-asir-mountains-view.webp",
  heroImageAlt: "Abha and the Asir mountains — private taxi service in Saudi Arabia's highland tourism region",
  serviceAreas: [
    { name: "Abha city centre & Lake Park", note: "The central, walkable core and the city's most popular family gathering spot." },
    { name: "Al Souda highlands", note: "Saudi Arabia's highest point, reached by a scenic mountain road above the city." },
    { name: "Habala village access point", note: "The cable car station serving the former hanging village." },
  ],
  hotelZones: [
    { name: "Abha city-centre hotels", note: "The most convenient base for Lake Park and central attractions." },
    { name: "Al Souda highland stays", note: "Higher-elevation accommodation for visitors prioritising the coolest possible climate." },
    { name: "Khamis Mushait overflow hotels", note: "A short drive from Abha, useful during peak summer season when the city's hotels fill up." },
  ],
  airportNote: "Abha International Airport sits about 22km from the city — allow extra buffer time during the Asir summer festival season, when demand and traffic both peak.",
  practicalInfo: [
    { title: "Peak summer season", note: "June–August draws a steady wave of domestic tourism as visitors escape the heat elsewhere — book ahead, as hotels and drivers both get busier." },
    { title: "Winter mist", note: "Mountain roads can see fog in winter months; our drivers are experienced with the conditions." },
    { title: "Cable car timing", note: "Al Souda and Habala both get queues at peak times — an early or late booking usually means shorter waits." },
  ],
};
