import type { RouteData } from "@/components/RoutePage";

/* ── 1. Dammam Airport → Bahrain ────────────────────────────── */
export const dammamAirportToBahrain: RouteData = {
  slug: "dammam-airport-to-bahrain-taxi-service",
  origin: "Dammam Airport",
  destination: "Bahrain",
  isCrossBorder: true,
  borderCrossingName: "King Fahd Causeway",
  eyebrow: "Airport to Border Transfer",
  h1: "Dammam Airport to Bahrain Taxi Service",
  intro: "Direct taxi transfer from King Fahd International Airport (DMM) to the King Fahd Causeway and on to Bahrain. Meet-and-greet pickup, fixed pricing, and drivers experienced with the busiest GCC land crossing.",
  breadcrumbLabel: "Dammam Airport → Bahrain",
  distance: "~65 km",
  travelTime: "1 – 1.5 hours (incl. causeway)",
  heroImage: "/images/airport-terminal.jpg",
  overviewTitle: "Fastest Way from Dammam Airport to Bahrain",
  overviewParagraphs: [
    "Landing at King Fahd International Airport and heading straight to Bahrain is one of the most common cross-border trips in the Eastern Province. Our drivers meet you at DMM arrivals and take the direct route onto the King Fahd Causeway — the 25 km bridge connecting Saudi Arabia to Bahrain — avoiding the need to first transit through Dammam or Khobar city traffic.",
    "The causeway itself has its own passport control and customs point roughly midway across. Our vehicles are causeway-permitted and our drivers know the lanes, peak-hour patterns, and documentation checks so your crossing is as fast as possible.",
    "Because private taxis do not cross into Bahraini territory, we take you to the Saudi exit point / Bahraini entry plaza on the causeway, where — if requested in advance — we coordinate a licensed Bahrain-side driver to continue your journey into Manama or onward to your hotel, seamlessly and without you needing to arrange anything yourself.",
  ],
  borderProcessTitle: "King Fahd Causeway Crossing Process",
  borderProcessParagraphs: [
    "After landing at DMM, your driver will be waiting at arrivals with a name sign. The drive to the causeway entry point takes roughly 45–55 minutes from the airport, mostly via the Dammam–Al Khobar coastal highway.",
    "At the Saudi exit checkpoint, all passengers present passports and GCC nationals present their national ID. Vehicle documentation is checked, and a toll/passage fee applies at the Saudi side gate before crossing onto the bridge itself.",
    "On the Bahrain side, passport control issues an entry stamp or checks your pre-approved eVisa. Most nationalities can obtain a Bahrain visa on arrival or eVisa online in advance — we recommend applying at least 48 hours before travel to avoid delays.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Bahrain eVisa or visa-on-arrival eligibility confirmation",
    "GCC national ID (for Saudi/Bahraini/GCC citizens)",
    "Iqama or valid Saudi residency proof (for expatriates)",
    "Confirmed pickup flight number and drop-off address",
  ],
  pickupPoints: ["DMM Airport arrivals hall (Terminal 1)", "Dammam city hotels", "Al Khobar Corniche hotels", "Dhahran business district", "Half Moon Bay resorts"],
  dropoffInfo: "Standard drop-off is at the King Fahd Causeway Bahrain-side plaza, with optional coordinated onward transfer into Manama, Seef District, or Bahrain International Airport arranged in advance via our partner network.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Ideal for solo or couple airport-to-causeway transfers." },
    { name: "SUV", capacity: "1–5 passengers", note: "Extra luggage space for longer Bahrain stays." },
    { name: "Van", capacity: "6–10 passengers", note: "Best for families or groups crossing together." },
  ],
  faqs: [
    { q: "Can your taxi drive all the way into Manama?", a: "Saudi-plated private taxis cannot legally cross into Bahraini territory. We drop you at the Bahrain-side plaza of the King Fahd Causeway, and can pre-arrange a licensed Bahrain driver to continue your journey seamlessly." },
    { q: "Do I need a visa before arriving at the causeway?", a: "Most nationalities can get a Bahrain eVisa online in advance or a visa-on-arrival at the causeway checkpoint. GCC nationals cross with just their national ID. We recommend confirming your visa route 48 hours before travel." },
    { q: "How long does the causeway crossing itself take?", a: "The 25 km bridge takes about 20–30 minutes to drive, but total crossing time including passport and customs checks is usually 45–75 minutes depending on traffic and time of day." },
    { q: "Can you pick me up for a late-night DMM flight arrival?", a: "Yes, we operate 24/7. Late-night causeway crossings are quieter and often faster than daytime, though visa counters may have reduced staffing after midnight." },
    { q: "What's the best time of day to cross to avoid queues?", a: "Weekday mornings (before 10am) and late evenings are typically fastest. Thursday and Friday evenings see the heaviest weekend leisure traffic." },
  ],
  relatedRoutes: [
    { href: "/bahrain-to-dammam-taxi-service", label: "Bahrain to Dammam Taxi" },
    { href: "/saudi-arabia-to-bahrain-taxi-service", label: "Saudi Arabia to Bahrain Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/dammam-airport-taxi-service", label: "Dammam Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Ready to Cross to Bahrain?",
};

/* ── 2. Dammam Airport → Khafji ─────────────────────────────── */
export const dammamAirportToKhafji: RouteData = {
  slug: "dammam-airport-to-khafji-taxi-service",
  origin: "Dammam Airport",
  destination: "Khafji",
  isCrossBorder: false,
  eyebrow: "Airport to Border Town Transfer",
  h1: "Dammam Airport to Khafji Taxi Service",
  intro: "Comfortable intercity transfer from King Fahd International Airport to Khafji, Saudi Arabia's northernmost Gulf coast city and the gateway crossing point to Kuwait. Direct highway route, fixed pricing, and drivers familiar with the Al Khafji corridor.",
  breadcrumbLabel: "Dammam Airport → Khafji",
  distance: "~180 km",
  travelTime: "2 – 2.5 hours",
  heroImage: "/images/airport-terminal.jpg",
  overviewTitle: "Direct Transfer to Khafji from King Fahd International Airport",
  overviewParagraphs: [
    "Khafji sits at the northern tip of Saudi Arabia's Eastern Province, on the Gulf coast facing Kuwait. It's a key stop for travelers connecting onward to Kuwait, for workers in the Khafji Joint Operations oil zone, and for visitors exploring the Neutral Zone heritage of the area.",
    "The drive from Dammam Airport follows Highway 95 north along the coast through Jubail and Ras Tanura before reaching Khafji — a straightforward, well-maintained route that takes roughly two hours outside of peak periods.",
    "Because Khafji is inside Saudi Arabia, this is a domestic transfer with no border formalities — just a smooth, direct highway drive. It's the ideal first leg for travelers planning to continue on to the Kuwait border via our companion Khafji to Kuwait service.",
  ],
  documents: [
    "Valid ID or passport (for identification purposes only — no border crossing on this route)",
    "Confirmed flight number for airport pickup",
    "Destination address or hotel name in Khafji",
  ],
  pickupPoints: ["DMM Airport arrivals hall", "Jubail Industrial City (en route stop available)", "Ras Tanura area", "Al Khafji city center", "Khafji Joint Operations compound"],
  dropoffInfo: "We drop off directly at your Khafji hotel, residential compound, or business address — including the Khafji Joint Operations (KJO) area for oil and gas industry travelers.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Comfortable for the 2-hour coastal highway drive." },
    { name: "SUV", capacity: "1–5 passengers", note: "Popular with KJO business travelers needing extra space." },
    { name: "Van", capacity: "6–10 passengers", note: "For crews or families traveling together to Khafji." },
  ],
  faqs: [
    { q: "Is this route a border crossing?", a: "No — Khafji is a Saudi city, so this is a straightforward domestic transfer. No passport control or customs formalities apply on this leg of the journey." },
    { q: "How far is Khafji from the Kuwait border?", a: "Khafji sits right at the Saudi–Kuwait border. If you need to continue into Kuwait, book our dedicated Khafji to Kuwait taxi service for the cross-border leg." },
    { q: "Do you serve the Khafji Joint Operations (KJO) compound?", a: "Yes, we regularly transfer oil and gas industry travelers to and from the KJO compound and surrounding accommodation." },
    { q: "Can I stop in Jubail on the way?", a: "Yes, a short stop in Jubail Industrial City can be arranged along the route at no extra routing complexity — just mention it when booking." },
    { q: "Is the highway to Khafji well maintained?", a: "Yes, Highway 95 along the Gulf coast is a modern, well-signed dual carriageway for the entire route from Dammam to Khafji." },
  ],
  relatedRoutes: [
    { href: "/khafji-to-kuwait-taxi-service", label: "Khafji to Kuwait Taxi" },
    { href: "/dammam-to-kuwait-taxi-service", label: "Dammam to Kuwait Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/dammam-airport-taxi-service", label: "Dammam Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Khafji Transfer",
};

/* ── 3. Dammam Airport → Qatar ──────────────────────────────── */
export const dammamAirportToQatar: RouteData = {
  slug: "dammam-airport-to-qatar-taxi-service",
  origin: "Dammam Airport",
  destination: "Qatar",
  isCrossBorder: true,
  borderCrossingName: "Salwa / Abu Samra Border",
  eyebrow: "Airport to Border Transfer",
  h1: "Dammam Airport to Qatar Taxi Service",
  intro: "Direct land transfer from King Fahd International Airport in Dammam to Doha, Qatar, via the Salwa (Abu Samra) border crossing. One vehicle, one driver, door-to-door — no need to change transport mid-journey.",
  breadcrumbLabel: "Dammam Airport → Qatar",
  distance: "~440 km",
  travelTime: "5 – 6 hours (incl. border)",
  heroImage: "/images/airport-terminal.jpg",
  overviewTitle: "Non-Stop Transfer from Dammam Airport to Doha",
  overviewParagraphs: [
    "Flying into King Fahd International Airport and continuing overland to Qatar is a popular option for business travelers, event attendees, and families who prefer a private, direct journey over connecting flights. Our service picks you up at DMM arrivals and drives the entire route to Doha in one vehicle.",
    "The route runs south through Al-Ahsa and Hofuf before reaching the Salwa border crossing (Abu Samra on the Qatari side) — the sole land gateway between the two countries, extensively upgraded in recent years to handle high passenger volumes efficiently.",
    "Unlike the Bahrain causeway, Saudi-registered vehicles with proper authorization are able to complete the full journey into Qatar, meaning your driver stays with you from DMM arrivals all the way to your Doha hotel, residence, or Hamad International Airport.",
  ],
  borderProcessTitle: "Salwa / Abu Samra Crossing Process",
  borderProcessParagraphs: [
    "From DMM Airport, the drive to the Salwa border takes roughly 3.5–4 hours via the Al-Ahsa route. We build in a rest stop along the way for longer journeys.",
    "At the Saudi exit post, passengers clear passport control and the vehicle undergoes a standard customs check. On the Qatari side at Abu Samra, travelers present a valid passport along with a Hayya Card (for event ticket holders) or an approved Qatar visa for non-GCC nationals.",
    "GCC nationals cross with just their national ID. The Abu Samra facility has been significantly modernized, and typical processing during off-peak hours is 30–60 minutes total for both sides combined.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Hayya Card or valid Qatar entry visa (non-GCC nationals)",
    "GCC national ID (for Saudi/Qatari/GCC citizens)",
    "Confirmed pickup flight details at DMM",
    "Doha drop-off address or hotel confirmation",
  ],
  pickupPoints: ["DMM Airport arrivals hall (Terminal 1)", "Dammam city hotels", "Al Khobar business district", "Al-Ahsa (en route stop available)", "Dhahran corporate offices"],
  dropoffInfo: "Direct door-to-door drop-off anywhere in Doha — hotels, residential towers, corporate offices, or Hamad International Airport (DOH) for onward connections.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Comfortable for the long-distance drive with reclining seats." },
    { name: "SUV", capacity: "1–5 passengers", note: "Extra legroom and luggage space for the 5–6 hour journey." },
    { name: "Van", capacity: "6–10 passengers", note: "Popular for event groups and families heading to Doha." },
  ],
  faqs: [
    { q: "Does the driver stay with me for the whole trip to Doha?", a: "Yes. Unlike the Bahrain causeway route, our vehicles and drivers are authorized to complete the full journey from DMM Airport into Qatar and to your final Doha address." },
    { q: "Do I need a Hayya Card for this route?", a: "A Hayya Card is required only if you're attending an event that issues one; otherwise a standard Qatar visa or GCC national ID applies. Check current entry requirements before booking." },
    { q: "How long is the total trip including the border?", a: "Typically 5–6 hours door-to-door, including the drive from DMM, the Salwa/Abu Samra crossing, and the final leg into Doha." },
    { q: "Is it cheaper than flying DMM to Doha?", a: "For groups of 2 or more, the private taxi is often comparable to or cheaper than multiple flight tickets, plus you avoid layovers and extra airport transfers on both ends." },
    { q: "Can I be dropped at Hamad International Airport instead of a hotel?", a: "Yes, we can route your drop-off directly to Hamad International Airport (DOH) if you have an onward connecting flight." },
  ],
  relatedRoutes: [
    { href: "/qatar-to-riyadh-taxi-service", label: "Qatar to Riyadh Taxi" },
    { href: "/saudi-arabia-to-qatar-taxi-service", label: "Saudi Arabia to Qatar Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/dammam-airport-taxi-service", label: "Dammam Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Doha Transfer",
};

/* ── 4. Dammam Airport → Riyadh ─────────────────────────────── */
export const dammamAirportToRiyadh: RouteData = {
  slug: "dammam-airport-to-riyadh-taxi-service",
  origin: "Dammam Airport",
  destination: "Riyadh",
  isCrossBorder: false,
  eyebrow: "Intercity Airport Transfer",
  h1: "Dammam Airport to Riyadh Taxi Service",
  intro: "Private intercity transfer from King Fahd International Airport straight to Riyadh — the capital's business district, government offices, or your hotel. Fixed pricing, executive vehicles, and door-to-door comfort on the Dammam–Riyadh highway.",
  breadcrumbLabel: "Dammam Airport → Riyadh",
  distance: "~400 km",
  travelTime: "3.5 – 4.5 hours",
  heroImage: "/images/airport-terminal.jpg",
  overviewTitle: "Direct Highway Transfer from Dammam Airport to Riyadh",
  overviewParagraphs: [
    "The Dammam–Riyadh corridor is one of Saudi Arabia's busiest intercity routes, connecting the Eastern Province's oil and logistics hub to the capital's government and financial center. Many executives, officials, and families prefer a private door-to-door transfer over a domestic connecting flight, especially with luggage or when arriving outside regular flight schedules.",
    "The route follows Highway 40, a modern, well-lit dual carriageway crossing the eastern desert plateau, with rest-stop facilities roughly at the midpoint near Al-Ahsa/Hofuf turnoff for longer journeys.",
    "Whether you're heading into KAFD, Olaya, Diriyah, or a government ministry appointment, our drivers plan the route around Riyadh's peak traffic hours to get you to your exact destination efficiently.",
  ],
  documents: [
    "Valid ID or passport for identification",
    "Confirmed flight number for airport pickup",
    "Riyadh drop-off address or hotel confirmation",
  ],
  pickupPoints: ["DMM Airport arrivals hall (Terminal 1)", "Dammam city hotels", "Al Khobar business district", "Dhahran corporate offices", "King Fahd Causeway (combined itineraries)"],
  dropoffInfo: "Direct drop-off anywhere in Riyadh — KAFD, Olaya, Diriyah, government ministries, or King Khalid International Airport (RUH) for onward connections.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Ideal for solo executive travel between the two cities." },
    { name: "SUV", capacity: "1–5 passengers", note: "Popular for families and business teams with extra luggage." },
    { name: "Van", capacity: "6–10 passengers", note: "Best for corporate groups traveling together to Riyadh." },
  ],
  faqs: [
    { q: "Is it faster to fly or take a private taxi from Dammam to Riyadh?", a: "Flying is faster in the air, but once you factor in check-in, security, and baggage collection at both airports, a direct door-to-door taxi (3.5–4.5 hours) is often comparable in total time and far more convenient with luggage." },
    { q: "Can you arrange a corporate account for regular Dammam–Riyadh transfers?", a: "Yes, we offer monthly invoiced corporate accounts for businesses that regularly move staff between the Eastern Province and Riyadh." },
    { q: "Do you offer a rest stop on the way?", a: "Yes, drivers can stop near the Al-Ahsa/Hofuf area roughly midway if requested, or continue non-stop if you prefer the fastest transfer." },
    { q: "Can I book a late-night pickup after an international DMM arrival?", a: "Yes, we run 24/7. Overnight departures also mean lighter traffic and a smoother drive into Riyadh." },
    { q: "Do you serve King Khalid International Airport as a drop-off?", a: "Yes, if you have an onward flight from Riyadh, we can drop you directly at RUH instead of a city address." },
  ],
  relatedRoutes: [
    { href: "/riyadh-to-dammam-guide", label: "Riyadh to Dammam Travel Guide" },
    { href: "/services/riyadh", label: "Riyadh Taxi Service" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/dammam-airport-taxi-service", label: "Dammam Airport Taxi Service" },
    { href: "/riyadh-airport-taxi-service", label: "Riyadh Airport Taxi Service" },
  ],
  ctaText: "Book Your Riyadh Transfer",
};

/* ── 5. Bahrain → Dammam ────────────────────────────────────── */
export const bahrainToDammam: RouteData = {
  slug: "bahrain-to-dammam-taxi-service",
  origin: "Bahrain",
  destination: "Dammam",
  isCrossBorder: true,
  borderCrossingName: "King Fahd Causeway",
  eyebrow: "Border Crossing Transfer",
  h1: "Bahrain to Dammam Taxi Service",
  intro: "Coordinated transfer from Bahrain across the King Fahd Causeway into Dammam, Saudi Arabia — with a Bahrain-side driver taking you to the border and a Saudi partner vehicle continuing seamlessly into the Eastern Province.",
  breadcrumbLabel: "Bahrain → Dammam",
  distance: "~65 km",
  travelTime: "1 – 1.5 hours (incl. causeway)",
  heroImage: "/images/chauffeur.jpg",
  overviewTitle: "Coordinated Crossing from Bahrain into Dammam",
  overviewParagraphs: [
    "Traveling from Manama, Seef, or anywhere in Bahrain into Saudi Arabia's Eastern Province is a frequent trip for shoppers, families, weekend visitors, and business travelers. The King Fahd Causeway is the only land link between the two countries, and getting the logistics right on both sides makes the difference between a smooth trip and a frustrating one.",
    "We coordinate the full journey: a licensed Bahrain-side driver collects you from your hotel or residence and takes you to the causeway checkpoint. Once you clear Saudi passport control and customs on the far side, our Dammam-based driver is waiting to continue your journey directly into the city.",
    "This handover system exists because private taxis are not permitted to cross international borders — but with advance booking, the transition at the causeway is coordinated so you barely notice the switch between vehicles.",
  ],
  borderProcessTitle: "Crossing from Bahrain to Saudi Arabia",
  borderProcessParagraphs: [
    "Your Bahrain-side pickup driver takes you to the causeway entry point, roughly 20–25 minutes from central Manama depending on traffic.",
    "At the Bahrain exit post, standard passport checks apply. On the Saudi side, GCC nationals cross with a national ID; other nationalities need a valid Saudi visa or Iqama (residency permit) if returning as a resident.",
    "After clearing Saudi immigration and customs, you'll be met by our waiting Dammam-side vehicle for the final leg into the city — typically a further 25–35 minutes to central Dammam, Khobar, or Dhahran.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Saudi visa, Iqama (residency permit), or GCC national ID",
    "Confirmed Bahrain pickup address and time",
    "Dammam/Khobar/Dhahran drop-off address",
  ],
  pickupPoints: ["Manama hotels", "Seef District", "Bahrain International Airport", "Juffair area", "Amwaj Islands"],
  dropoffInfo: "Standard onward drop-off anywhere in Dammam, Al Khobar, or Dhahran — hotels, residential compounds, or King Fahd International Airport for onward flights.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Efficient for solo or couple crossings into Dammam." },
    { name: "SUV", capacity: "1–5 passengers", note: "Extra space for shopping trips and family visits." },
    { name: "Van", capacity: "6–10 passengers", note: "For families or groups making the trip together." },
  ],
  faqs: [
    { q: "Will I need to change vehicles at the causeway?", a: "Yes — Bahrain-plated and Saudi-plated taxis cannot cross the border themselves, so a handover happens at the causeway checkpoint. We coordinate the timing so both drivers meet you with minimal wait." },
    { q: "Do GCC nationals need a visa to enter Saudi Arabia this way?", a: "No, GCC nationals cross with just their national ID. Other nationalities need a valid Saudi visa or valid Iqama if returning as a resident." },
    { q: "Can you drop me directly at Dammam Airport for a flight?", a: "Yes, we can route your final drop-off to King Fahd International Airport instead of a city address if you have an onward flight." },
    { q: "How far in advance should I book a Bahrain to Dammam transfer?", a: "We recommend booking at least 24 hours ahead so we can properly coordinate both the Bahrain-side and Saudi-side vehicles for a smooth handover." },
    { q: "Is the causeway busy on weekends?", a: "Yes, Thursday and Friday evenings see the heaviest weekend leisure traffic in both directions. Weekday mornings are typically the quickest time to cross." },
  ],
  relatedRoutes: [
    { href: "/dammam-airport-to-bahrain-taxi-service", label: "Dammam Airport to Bahrain Taxi" },
    { href: "/saudi-arabia-to-bahrain-taxi-service", label: "Saudi Arabia to Bahrain Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/riyadh-to-bahrain-taxi-service", label: "Riyadh to Bahrain Taxi" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Crossing to Dammam",
};

/* ── 6. Qatar → Riyadh ──────────────────────────────────────── */
export const qatarToRiyadh: RouteData = {
  slug: "qatar-to-riyadh-taxi-service",
  origin: "Qatar",
  destination: "Riyadh",
  isCrossBorder: true,
  borderCrossingName: "Salwa / Abu Samra Border",
  eyebrow: "Long-Distance Border Transfer",
  h1: "Qatar to Riyadh Taxi Service",
  intro: "Private door-to-door transfer from Doha, Qatar, to Riyadh, Saudi Arabia's capital, via the Salwa (Abu Samra) land border. One vehicle for the entire journey — no layovers, no changing rides, direct to your Riyadh destination.",
  breadcrumbLabel: "Qatar → Riyadh",
  distance: "~580 km",
  travelTime: "6.5 – 7.5 hours (incl. border)",
  heroImage: "/images/chauffeur.jpg",
  overviewTitle: "Non-Stop Land Transfer from Doha to Riyadh",
  overviewParagraphs: [
    "For business travelers, diplomatic missions, and families who prefer a private overland journey to flying, the Doha–Riyadh route is a long but comfortable drive across the Salwa border into the heart of Saudi Arabia. It's especially popular around major events, GCC summits, and for travelers avoiding connecting flights.",
    "The journey departs Doha westward to the Abu Samra border post, crosses into Saudi Arabia at Salwa, then continues north-west across the Eastern Province and central desert plateau to Riyadh — one continuous route covered by a single vehicle and driver.",
    "Given the distance, we build in a scheduled rest stop roughly midway (typically near Al-Ahsa or Hofuf), and offer executive vehicles with extra legroom for the multi-hour drive.",
  ],
  borderProcessTitle: "Salwa / Abu Samra Crossing on This Route",
  borderProcessParagraphs: [
    "From central Doha, the drive to Abu Samra takes around 1 hour. Passengers present passports for Qatari exit formalities before proceeding to the Saudi entry post at Salwa.",
    "GCC nationals cross with their national ID; other nationalities need a valid Saudi visa. Vehicle customs checks apply on both sides, and the crossing typically takes 30–60 minutes combined during off-peak hours.",
    "After clearing into Saudi Arabia, the remaining drive to Riyadh continues via Al-Ahsa and the eastern highway network — roughly 5 hours from the border to the capital.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Saudi entry visa or GCC national ID",
    "Qatar exit clearance (standard for residents/visitors)",
    "Riyadh drop-off address or hotel confirmation",
    "Flight or onward travel details if applicable",
  ],
  pickupPoints: ["Doha hotels (West Bay, The Pearl)", "Hamad International Airport", "Lusail", "Al Wakrah", "Doha corporate offices"],
  dropoffInfo: "Direct drop-off anywhere in Riyadh — KAFD, Olaya, Diriyah, government ministries, or King Khalid International Airport for onward connections.",
  vehicleOptions: [
    { name: "Executive Sedan", capacity: "1–3 passengers", note: "Reclining seats and extra comfort for the 7-hour journey." },
    { name: "SUV", capacity: "1–5 passengers", note: "Popular for families and business travelers with luggage." },
    { name: "Van", capacity: "6–10 passengers", note: "For delegations or groups traveling together to Riyadh." },
  ],
  faqs: [
    { q: "Is a single driver used for the entire Doha to Riyadh trip?", a: "Yes, one vehicle and driver cover the full route from Doha, through the Salwa border, to your final Riyadh destination — no vehicle changes required." },
    { q: "How long does the full journey take?", a: "Typically 6.5–7.5 hours including the border crossing and a scheduled rest stop, depending on traffic and border processing times." },
    { q: "Do I need a visa to enter Saudi Arabia from Qatar this way?", a: "Non-GCC nationals need a valid Saudi entry visa. GCC nationals can cross with just their national ID." },
    { q: "Can this trip be booked for a group or delegation?", a: "Yes, we regularly arrange multi-vehicle convoys for delegations, corporate groups, and event attendees traveling between Doha and Riyadh." },
    { q: "Is it better to fly or drive this route?", a: "Flying is faster overall, but for groups, those with excess luggage, or travelers who prefer privacy and flexibility over airport processes, the direct drive is a strong alternative." },
  ],
  relatedRoutes: [
    { href: "/dammam-airport-to-qatar-taxi-service", label: "Dammam Airport to Qatar Taxi" },
    { href: "/saudi-arabia-to-qatar-taxi-service", label: "Saudi Arabia to Qatar Taxi" },
    { href: "/services/riyadh", label: "Riyadh Taxi Service" },
    { href: "/riyadh-airport-taxi-service", label: "Riyadh Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Doha to Riyadh Transfer",
};

/* ── 7. Khafji → Kuwait ─────────────────────────────────────── */
export const khafjiToKuwait: RouteData = {
  slug: "khafji-to-kuwait-taxi-service",
  origin: "Khafji",
  destination: "Kuwait",
  isCrossBorder: true,
  borderCrossingName: "Al Khafji / Al Nuwaiseeb Border",
  eyebrow: "Border Crossing Transfer",
  h1: "Khafji to Kuwait Taxi Service",
  intro: "Direct taxi transfer from Al Khafji, Saudi Arabia, across the Al Nuwaiseeb border crossing into Kuwait. The shortest and most direct land route between the two countries — ideal for business travelers, workers, and families.",
  breadcrumbLabel: "Khafji → Kuwait",
  distance: "~15 km to border / ~180 km to Kuwait City",
  travelTime: "2.5 – 3 hours (incl. border)",
  heroImage: "/images/fleet-suv.jpg",
  overviewTitle: "Shortest Land Route from Saudi Arabia into Kuwait",
  overviewParagraphs: [
    "Al Khafji, Saudi Arabia's northernmost Gulf coast city, sits just a short drive from the Al Nuwaiseeb border crossing — the primary land gateway into Kuwait for travelers, commuters, and the region's oil and gas workforce. It's the most direct crossing point between the two countries, far shorter than routing via Riyadh.",
    "Our drivers handle the short approach from Khafji to the border, guide you through the crossing, and continue the drive north into Kuwait — typically ending in Kuwait City, Al Ahmadi, or Fahaheel depending on your destination.",
    "This route is especially popular with GCC nationals, cross-border commuters working in the joint Neutral Zone oil fields, and families with connections on both sides of the border.",
  ],
  borderProcessTitle: "Al Nuwaiseeb Border Crossing Process",
  borderProcessParagraphs: [
    "From Khafji city center, the drive to the Saudi exit checkpoint takes about 15–20 minutes. Passengers present passports and vehicle documents at the Saudi post.",
    "GCC nationals cross with their national ID card — no passport stamp required in most cases. Non-GCC nationals need a valid Kuwait entry visa, which can often be arranged as a visa-on-arrival for eligible passport holders or in advance online.",
    "The crossing is open 24 hours and well-equipped for regular commuter and commercial traffic. Processing typically takes 30–90 minutes outside peak periods, but can extend to several hours on Thursday/Friday evenings and public holidays — we plan pickup times around known busy windows where possible. A mandatory third-party vehicle insurance policy and a small road toll are purchased at the border complex before crossing.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Kuwait entry visa or visa-on-arrival eligibility (non-GCC nationals)",
    "GCC national ID (for Saudi/Kuwaiti/GCC citizens)",
    "Iqama or Saudi residency proof (for expatriates)",
    "Cash (Kuwaiti Dinar) for border toll and mandatory vehicle insurance — cards often accepted as backup",
    "Kuwait drop-off address confirmation",
  ],
  pickupPoints: ["Al Khafji city center", "Khafji Joint Operations (KJO) compound", "Khafji hotels", "Ras Al Khafji coastal area"],
  dropoffInfo: "Direct drop-off in Kuwait City, Al Ahmadi, Fahaheel, or Kuwait International Airport for onward connections.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Quick and efficient for the short border crossing route." },
    { name: "SUV", capacity: "1–5 passengers", note: "Popular with oil and gas industry commuters." },
    { name: "Van", capacity: "6–10 passengers", note: "For crews and families crossing together." },
  ],
  faqs: [
    { q: "Is Al Nuwaiseeb the closest crossing from Khafji to Kuwait?", a: "Yes, Al Nuwaiseeb (Al Khafji border post) is the primary and most direct land crossing between Saudi Arabia and Kuwait, just a short drive from Khafji city." },
    { q: "Do GCC nationals need a visa for this crossing?", a: "No, GCC nationals can cross with just their national ID card in most cases — no visa or passport stamp typically required." },
    { q: "Can non-GCC nationals get a visa on arrival at this border?", a: "Many nationalities are eligible for a Kuwait visa-on-arrival at land borders, but requirements change — we recommend confirming your specific eligibility before travel." },
    { q: "How long can the border crossing take?", a: "The Al Nuwaiseeb crossing runs 24 hours and is usually 30–90 minutes for passenger vehicles, but Thursday/Friday evenings and public holidays can see waits of 2–4 hours. We schedule pickups to avoid the worst peak windows where possible." },
    { q: "Is vehicle insurance required to cross?", a: "Yes, a mandatory third-party vehicle insurance policy and a small road toll are purchased at the border complex before entering Kuwait — this is included in our service and handled by your driver." },
    { q: "Do you serve workers commuting to the Neutral Zone oil fields?", a: "Yes, this route is regularly used by workers and contractors in the shared Saudi-Kuwait Neutral Zone oil operations, and we're familiar with the schedules and pickup points involved." },
    { q: "Can I combine this with a Dammam Airport pickup?", a: "Yes — book our Dammam Airport to Khafji service first, then continue with this Khafji to Kuwait leg, or ask us to arrange the combined itinerary in one booking." },
  ],
  relatedRoutes: [
    { href: "/dammam-airport-to-khafji-taxi-service", label: "Dammam Airport to Khafji Taxi" },
    { href: "/dammam-to-kuwait-taxi-service", label: "Dammam to Kuwait Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Kuwait Border Crossing",
};

/* ── 8. Riyadh → Bahrain ────────────────────────────────────── */
export const riyadhToBahrain: RouteData = {
  slug: "riyadh-to-bahrain-taxi-service",
  origin: "Riyadh",
  destination: "Bahrain",
  isCrossBorder: true,
  borderCrossingName: "King Fahd Causeway",
  eyebrow: "Long-Distance Border Transfer",
  h1: "Riyadh to Bahrain Taxi Service",
  intro: "Private long-distance transfer from Riyadh across the King Fahd Causeway into Bahrain. A comfortable executive drive across the Eastern Province with a coordinated handover at the causeway for onward travel into Manama.",
  breadcrumbLabel: "Riyadh → Bahrain",
  distance: "~470 km",
  travelTime: "4.5 – 5.5 hours (incl. causeway)",
  heroImage: "/images/chauffeur.jpg",
  overviewTitle: "Direct Transfer from the Capital to Bahrain",
  overviewParagraphs: [
    "Travelers heading from Riyadh to Bahrain for business, weekend leisure trips, or family visits often prefer a private overland transfer to avoid connecting flights or airport-to-airport logistics on both ends. The route runs east across the Najd plateau to Dammam and Al Khobar before reaching the King Fahd Causeway.",
    "Our drivers cover the full Riyadh-to-causeway leg in an executive vehicle, then hand off at the Bahrain-side checkpoint to a coordinated partner driver who continues into Manama, Seef, or your final Bahrain destination — a smooth, pre-arranged transition.",
    "This route is popular around Bahrain Grand Prix weekends, GCC business travel, and family visits, when demand for reliable, private cross-border transport peaks.",
  ],
  borderProcessTitle: "Crossing the King Fahd Causeway from Riyadh",
  borderProcessParagraphs: [
    "The drive from Riyadh to the causeway entry point takes roughly 4 hours via Highway 40 through Al-Ahsa and Dammam. We schedule a rest stop along the way for comfort.",
    "At the Saudi exit checkpoint, GCC nationals cross with their national ID; other nationalities require a valid Saudi exit clearance if resident, or standard passport control if visiting.",
    "On the Bahrain side, entry is via eVisa, visa-on-arrival, or GCC ID depending on nationality. Our Bahrain-side partner driver meets you at the plaza for the final leg into the city.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Bahrain eVisa or visa-on-arrival eligibility confirmation",
    "GCC national ID (for Saudi/Bahraini/GCC citizens)",
    "Iqama or Saudi residency proof (for expatriates)",
    "Confirmed Bahrain drop-off address",
  ],
  pickupPoints: ["Riyadh hotels (Olaya, KAFD)", "King Khalid International Airport", "Diriyah", "Riyadh corporate offices"],
  dropoffInfo: "Coordinated onward drop-off anywhere in Bahrain — Manama, Seef District, Bahrain International Circuit, or Bahrain International Airport.",
  vehicleOptions: [
    { name: "Executive Sedan", capacity: "1–3 passengers", note: "Reclining seats for the long Riyadh-to-causeway leg." },
    { name: "SUV", capacity: "1–5 passengers", note: "Extra comfort and luggage space for the journey." },
    { name: "Van", capacity: "6–10 passengers", note: "For families or groups traveling together to Bahrain." },
  ],
  faqs: [
    { q: "How long is the full trip from Riyadh to Bahrain?", a: "Typically 4.5–5.5 hours total, including the drive to the causeway, the border crossing, and the coordinated handover into Bahrain." },
    { q: "Will I need to switch vehicles at the border?", a: "Yes, since Saudi-plated taxis cannot cross into Bahrain, we arrange a smooth handover to a licensed Bahrain-side driver at the causeway checkpoint." },
    { q: "Is this route busy during Bahrain Grand Prix weekends?", a: "Yes, demand and causeway traffic both increase significantly during F1 weekends — we recommend booking well in advance for those dates." },
    { q: "Can you arrange a return trip as well?", a: "Yes, round-trip bookings are available and often more convenient for short Bahrain visits — just let us know your return date when booking." },
    { q: "Do you offer executive vehicles for this route?", a: "Yes, we offer executive sedans with extra comfort features specifically suited to the longer Riyadh-to-Bahrain distance." },
  ],
  relatedRoutes: [
    { href: "/bahrain-to-dammam-taxi-service", label: "Bahrain to Dammam Taxi" },
    { href: "/saudi-arabia-to-bahrain-taxi-service", label: "Saudi Arabia to Bahrain Taxi" },
    { href: "/services/riyadh", label: "Riyadh Taxi Service" },
    { href: "/riyadh-airport-taxi-service", label: "Riyadh Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Bahrain Transfer",
};

/* ── 9. Dammam → Kuwait ─────────────────────────────────────── */
export const dammamToKuwait: RouteData = {
  slug: "dammam-to-kuwait-taxi-service",
  origin: "Dammam",
  destination: "Kuwait",
  isCrossBorder: true,
  borderCrossingName: "Al Khafji / Al Nuwaiseeb Border",
  eyebrow: "Border Crossing Transfer",
  h1: "Dammam to Kuwait Taxi Service",
  intro: "Direct door-to-door transfer from Dammam and the Eastern Province to Kuwait via the Al Nuwaiseeb border crossing at Khafji. A single vehicle covers the entire journey, ideal for business travelers, families, and oil industry commuters.",
  breadcrumbLabel: "Dammam → Kuwait",
  distance: "~530 km",
  travelTime: "5.5 – 6.5 hours (incl. border)",
  heroImage: "/images/fleet-suv.jpg",
  overviewTitle: "Direct Transfer from Dammam to Kuwait",
  overviewParagraphs: [
    "Dammam and the wider Eastern Province have deep business and family ties to Kuwait, with the Al Nuwaiseeb crossing near Khafji offering the most direct route north. Our service covers the full journey in one vehicle, avoiding the need to book separate legs or arrange your own onward transport.",
    "The drive follows the Gulf coast highway north through Jubail, Ras Tanura, and Khafji before reaching the Saudi–Kuwait border, then continues into Kuwait City or your specific destination such as Al Ahmadi or Fahaheel.",
    "This route is especially popular with corporate travelers, oil and gas sector employees, and families making regular visits between the two countries.",
  ],
  borderProcessTitle: "Crossing into Kuwait via Al Nuwaiseeb",
  borderProcessParagraphs: [
    "From Dammam, the drive to the border takes roughly 4.5–5 hours along the coastal Highway 95, passing through Jubail and Khafji.",
    "At the Saudi exit checkpoint, GCC nationals present their national ID, while other nationalities complete standard passport and exit formalities. Vehicle documentation is checked before crossing.",
    "On the Kuwaiti side at Al Nuwaiseeb, entry is via GCC ID for GCC nationals or a valid Kuwait visa/visa-on-arrival for eligible other nationalities. The crossing is open 24 hours and typically adds 30–90 minutes to the total journey, though Thursday/Friday evenings and holidays can see longer queues. A mandatory third-party vehicle insurance policy and small road toll are purchased at the border complex.",
  ],
  documents: [
    "Valid passport (6+ months validity)",
    "Kuwait entry visa or visa-on-arrival eligibility (non-GCC nationals)",
    "GCC national ID (for Saudi/Kuwaiti/GCC citizens)",
    "Iqama or Saudi residency proof (for expatriates)",
    "Confirmed Kuwait drop-off address",
  ],
  pickupPoints: ["Dammam city hotels", "Al Khobar Corniche", "Dhahran business district", "King Fahd International Airport", "Jubail Industrial City"],
  dropoffInfo: "Direct drop-off in Kuwait City, Al Ahmadi, Fahaheel, or Kuwait International Airport for onward connections.",
  vehicleOptions: [
    { name: "Sedan", capacity: "1–3 passengers", note: "Comfortable for the 5–6 hour coastal highway drive." },
    { name: "SUV", capacity: "1–5 passengers", note: "Popular with corporate travelers and families." },
    { name: "Van", capacity: "6–10 passengers", note: "For groups or families making the trip together." },
  ],
  faqs: [
    { q: "Does the same driver take me all the way to Kuwait City?", a: "Yes, one vehicle and driver cover the entire route from Dammam, through the Al Nuwaiseeb border, to your final Kuwait destination." },
    { q: "Is this faster than routing through Riyadh?", a: "Yes, the Khafji/Al Nuwaiseeb crossing is the most direct route from the Eastern Province into Kuwait — significantly shorter than routing via central Saudi Arabia." },
    { q: "Do you serve oil and gas industry travelers on this route?", a: "Yes, we regularly transfer corporate and industry travelers between the Eastern Province and Kuwait's business and energy sector hubs." },
    { q: "What documents do GCC nationals need?", a: "GCC nationals cross with just their national ID — no visa or passport stamp is typically required for this route." },
    { q: "Can I break the journey into two legs via Khafji?", a: "Yes, you can book our Dammam Airport to Khafji and Khafji to Kuwait services separately if you want a stopover, or book this combined direct route for a single non-stop journey." },
  ],
  relatedRoutes: [
    { href: "/khafji-to-kuwait-taxi-service", label: "Khafji to Kuwait Taxi" },
    { href: "/dammam-airport-to-khafji-taxi-service", label: "Dammam Airport to Khafji Taxi" },
    { href: "/services/dammam", label: "Dammam Taxi Service" },
    { href: "/dammam-airport-taxi-service", label: "Dammam Airport Taxi Service" },
    { href: "/border-crossing", label: "All Border Crossing Routes" },
  ],
  ctaText: "Book Your Kuwait Transfer",
};

export const allRoutes: RouteData[] = [
  dammamAirportToBahrain,
  dammamAirportToKhafji,
  dammamAirportToQatar,
  dammamAirportToRiyadh,
  bahrainToDammam,
  qatarToRiyadh,
  khafjiToKuwait,
  riyadhToBahrain,
  dammamToKuwait,
];
