import { generatePageMetadata } from "@/lib/seo";
import BlogPost from "@/components/BlogPost";
export const metadata = generatePageMetadata({ title: "Umrah Travel Planning Checklist", description: "Step-by-step Umrah travel checklist — visa, accommodation, transport, packing, and on-the-ground tips for a smooth pilgrimage.", path: "/blog/umrah-travel-planning", keywords: ["Umrah travel checklist", "Umrah planning guide", "Umrah preparation tips", "how to plan Umrah trip"] });
export default function Post() {
  return <BlogPost data={{ path: "/blog/umrah-travel-planning", title: "The Complete Umrah Travel Planning Checklist", category: "Religious Travel", date: "June 2025", excerpt: "Thorough preparation transforms Umrah from stressful logistics into a purely spiritual experience.", body: [
    { heading: "6 Months Before: Visa & Package", text: "Apply for your Umrah visa through a licensed Saudi travel agency. Umrah visas require a mahram declaration for women under 45 traveling without a male guardian. Book your package early — Ramadan packages sell out 4–6 months in advance. Compare packages that include accommodation near the Haram vs those further away." },
    { heading: "3 Months Before: Transport Booking", text: "Book all transport well in advance: Jeddah Airport to Makkah hotel, your Makkah–Madinah intercity transfer, and any Ziyarat tours. During peak Umrah months, transport availability drops and prices rise significantly. A complete Umrah Transport Package from Gulf Trip Service covers all these legs in a single booking." },
    { heading: "1 Month Before: Preparation", text: "Learn the Umrah rituals in detail — Tawaf, Sa'i, and halq/taqsir. Practice the duas you wish to make. If you have health conditions, consult your doctor about the physical demands of Tawaf (7 circumambulations around the Kaaba, up to 4km of walking). Pack modest, comfortable clothing for the Haram environment." },
    { heading: "Packing Essentials", text: "For men: ihram cloth (2 sets), unstitched sandals, small scissors. For women: modest loose abayas, comfortable walking shoes, multiple headscarves. For everyone: a small backpack for the Haram (lockers available), a printed copy of your booking confirmations, medication and prescriptions, and a power bank (the Haram has limited charging points)." },
    { heading: "On Arrival: What to Do First", text: "After landing at KAIA, your pre-booked driver will meet you at arrivals. If entering Ihram at the airport Meeqat, change before clearing customs. Keep your passport and booking references easily accessible. WhatsApp your driver as you collect luggage. The first priority is reaching your hotel and resting before Tawaf." },
  ]}} />;
}
