import { generatePageMetadata } from "@/lib/seo";
import BlogPost from "@/components/BlogPost";
export const metadata = generatePageMetadata({ title: "Best Family Destinations 2025", description: "Top family-friendly Saudi Arabia destinations — AlUla, Abha, Taif, Red Sea coast — with transport tips for each.", path: "/blog/family-saudi-destinations", keywords: ["family destinations Saudi Arabia", "Saudi Arabia family trip", "Abha family travel", "AlUla family visit"] });
export default function Post() {
  return <BlogPost data={{ path: "/blog/family-saudi-destinations", title: "Best Family Destinations in Saudi Arabia in 2025", category: "Travel Tips", date: "June 2025", excerpt: "Saudi Arabia has become one of the region's most compelling family travel destinations. Here are the best spots.", body: [
    { heading: "1. AlUla — Wonder & History Combined", text: "AlUla's ancient Nabataean tombs, dramatic rock formations, and Elephant Rock are genuinely awe-inspiring for children and adults alike. The Winter at Tantora festival (December–March) adds concerts and activities. Best for: families with children 8+. Transport: private transfer from AlUla Airport, then a dedicated driver for site visits." },
    { heading: "2. Abha & the Asir Highlands", text: "At 2,200m elevation, Abha is Saudi Arabia's coolest summer destination. The Al-Soudah cable car, Habala hanging village, and lush Asir escarpment are unlike anywhere else in the Kingdom. Best for: families with children of all ages. Transport: Abha Airport transfer, then local mountain driver for full-day excursions." },
    { heading: "3. Taif — The City of Roses", text: "Taif is perfect for a family day trip from Makkah or Jeddah. The Al-Hada cable car, honey markets, rose farms, and cool mountain air make it a favourite for Saudi families escaping summer heat. Best for: families with young children. Transport: direct Makkah–Taif or Jeddah–Taif private transfer." },
    { heading: "4. Jeddah Corniche & Waterfront", text: "The Jeddah waterfront offers a relaxed, family-friendly atmosphere with parks, cycling tracks, seafood restaurants, and the world's tallest fountain. Al-Shallal Theme Park is ideal for children aged 5–16. Best for: all family types. Transport: Jeddah city taxi with hourly or half-day booking." },
    { heading: "5. Riyadh Boulevard & Diriyah", text: "Riyadh Boulevard City hosts year-round entertainment. Diriyah's UNESCO mudbrick city is genuinely fascinating for older children interested in history. Riyadh Season (October–February) adds world-class events. Best for: families with teens. Transport: Riyadh city transfers with our fixed-rate service." },
  ]}} />;
}
