import { generatePageMetadata } from "@/lib/seo";
import BlogPost from "@/components/BlogPost";
export const metadata = generatePageMetadata({ title: "Top 10 Attractions in Riyadh", description: "From Diriyah to Boulevard World — the essential Riyadh attractions for tourists, first-time visitors, and returning travelers.", path: "/blog/top-attractions-riyadh", keywords: ["Riyadh attractions", "things to do in Riyadh", "Riyadh tourist guide", "Diriyah Riyadh visit"] });
export default function Post() {
  return <BlogPost data={{ path: "/blog/top-attractions-riyadh", title: "Top 10 Attractions in Riyadh You Must Visit", category: "Destinations", date: "June 2025", excerpt: "Riyadh has transformed into one of the Middle East's most dynamic city destinations. Here are the 10 experiences you cannot miss.", body: [
    { heading: "1. Diriyah — UNESCO World Heritage Site", text: "The birthplace of the Saudi state and a UNESCO World Heritage Site, Diriyah's At-Turaif district is a stunning mudbrick heritage city. The ongoing Diriyah Gate development project is turning it into a full destination. Allow at least half a day. Best visited in late afternoon for golden hour photography." },
    { heading: "2. Kingdom Centre Tower Sky Bridge", text: "The observation deck of the Kingdom Centre Tower offers a 360-degree panorama across Riyadh from 300m. The rose-gold glass sky bridge is an architectural icon and a photography landmark. Located in the Olaya district — easily reached via our Riyadh taxi service." },
    { heading: "3. National Museum of Saudi Arabia", text: "One of the best museums in the Arabian Peninsula, covering Saudi history from pre-Islamic civilisations through the founding of the Kingdom and Vision 2030. Eight themed halls with interactive exhibits. Free entry on Saturdays." },
    { heading: "4. Boulevard Riyadh City", text: "A 2.5km open-air entertainment complex with restaurants, concerts, rides, and events running throughout the year. The Boulevard World zone recreates iconic city scenes from Paris, New York, and Tokyo. Extremely popular with families on weekends." },
    { heading: "5. Al-Faisaliah Tower Observation Globe", text: "The golden globe at the top of Al-Faisaliah Tower houses a restaurant and observation area. Located opposite Kingdom Centre in the Olaya commercial district — a short transfer from most Riyadh hotels." },
    { heading: "6. Masmak Fortress", text: "The historic mudbrick fort in central Riyadh where Ibn Saud's warriors launched the 1902 capture of Riyadh. A significant moment in Saudi history, well presented with artefacts, weapons, and historical narrative. In Al-Dira district, walkable from the old markets." },
    { heading: "7. Al-Zal & Al-Dira Souq", text: "The original Riyadh market district — antiques, gold, textiles, and traditional Saudi handicrafts. Less tourist-polished than modern malls and far more authentic. Best visited on a cooler morning with a return taxi booked for when you're ready to leave." },
    { heading: "8. King Abdullah Park & Riyadh Season Venues", text: "Riyadh Season (October–February) transforms multiple entertainment zones across the city into world-class festival venues. Check the official programme before your visit — concerts, exhibitions, and regional celebrations fill hundreds of events." },
    { heading: "9. Wadi Hanifa & Green Riyadh", text: "Riyadh's greening project has transformed the desert valley of Wadi Hanifa into a 120km linear park. Cycling paths, picnic areas, and dramatic escarpment views make it a surprising contrast to the urban core. Accessible via transfer from any Riyadh hotel." },
    { heading: "10. The Edge of the World (Jebel Fihrayn)", text: "90km from Riyadh, the Edge of the World is a dramatic escarpment offering one of Saudi Arabia's most stunning vistas — an abrupt cliff dropping 300m to an ancient seabed. Accessible only by 4WD. We can arrange full-day transfers with an experienced desert driver." },
  ]}} />;
}
