import { generatePageMetadata } from "@/lib/seo";
import BlogPost from "@/components/BlogPost";
export const metadata = generatePageMetadata({ title: "AlUla Complete Travel Guide", description: "The only AlUla guide you need — itinerary planning, Hegra access, best accommodation, transport, and photography tips.", path: "/blog/alula-complete-guide", keywords: ["AlUla travel guide", "Hegra visit guide", "AlUla itinerary", "Elephant Rock AlUla"] });
export default function Post() {
  return <BlogPost data={{ path: "/blog/alula-complete-guide", title: "AlUla Complete Travel Guide: Hegra, Elephant Rock & Beyond", category: "Destinations", date: "June 2025", excerpt: "Saudi Arabia's most awe-inspiring destination deserves more than a day trip. Here's how to experience AlUla properly.", body: [
    { heading: "Why AlUla Is Unlike Anywhere Else", text: "AlUla is Saudi Arabia's cultural and archaeological crown jewel. The landscape — orange sandstone monoliths, ancient Nabataean tombs, oasis farms — feels like Jordan's Petra combined with Utah's canyon country. The scale is vast: over 200,000 years of human habitation across a 22,000 sq km heritage area." },
    { heading: "Hegra (Madain Saleh): Saudi Arabia's Petra", text: "Hegra is Saudi Arabia's first UNESCO World Heritage Site — a Nabataean city of 111 rock-cut tombs dating to the 1st century AD. Visits require a licensed guide (bookable through Experience AlUla). Entry is timed to protect the monuments. We transfer guests from AlUla Old Town to the Hegra Visitor Centre, approximately 20 minutes." },
    { heading: "Elephant Rock (Jabal Al-Fil)", text: "The natural rock formation resembling an elephant is AlUla's most-photographed landmark. Golden hour — one hour before sunset — transforms the sandstone into vivid orange. Accessible by vehicle and a short walk. No guide required. We time transfers to arrive exactly at golden hour." },
    { heading: "Suggested 4-Day AlUla Itinerary", text: "Day 1: Arrive AlUla Airport, check in, AlUla Old Town evening stroll. Day 2: Full Hegra tour (morning, guided). Day 3: Elephant Rock at golden hour, Dadan ancient city, Jabal Ikmah open library. Day 4: Ashar Arts District, Maraya Concert Hall exterior, depart. All site transfers are booked through Gulf Trip Service." },
    { heading: "Best Time to Visit AlUla", text: "November to March is ideal — temperatures of 15–25°C allow comfortable exploration. The Winter at Tantora festival (December–March) adds world-class concerts at Maraya. Summer (June–September) is hot (38–42°C) and most outdoor activities are limited to early mornings." },
  ]}} />;
}
